### ISSUE TITLE
TOC links in README on PyPI don't work

### ISSUE THREAD

**Issue by mhucka** [GillesPy2/GillesPy2#214]
The links in the TOC on the [GillesPy2 page on PyPI](https://pypi.org/project/gillespy2) does not work.

**Comment by makdl** [comment]
This issue seems to be related to Warehouse, the software powering PyPi, not supporting internal links for long_descriptions in Markdown as noted by this issue/feature request. https://github.com/pypa/warehouse/issues/4064

I unsuccessfully attempted to fix this issue by converting the README to reStructuredText. Our README makes use of several raw directives to embed HTML. Warehouse does not support raw directives in reStructuredText. https://packaging.python.org/guides/distributing-packages-using-setuptools/#uploading-your-project-to-pypi

A third and final attempt I tried to circumvient these limitations was to convert the embedded HTML to equivalent reStructuredText directives. GitHub ignores reStructuredText image width and height directives as noted by this issue. https://github.com/github/markup/issues/295

Given this information it appears no matter what, something will break in the README on either GitHub or PyPi.

For now I am going to close this issue. If anyone can think of a solution, please leave a comment.
