### ISSUE TITLE
Reaction error need to tell users to use "propensity_function" if they want to use more than 2 species in a reaction.

### ISSUE THREAD

**Issue by smrfeld** [GillesPy2/GillesPy2#256]
I tried to add a reaction with three reactants and got:
```
 raise ReactionError("Reaction: A mass-action reaction cannot involve more than two of one species or one "
gillespy2.core.gillespyError.ReactionError: Reaction: A mass-action reaction cannot involve more than two of one species or one of two species.
```
Are there any plans to support this? It is perfectly possible to have reactions with any number of reactants via Gillespie SSA.

**Comment by briandrawert** [comment]
GillesPy2 absolutely supports reactions with arbitrary number of reactants.  The problem is that the "mass-action" theory only works for 0, 1, or 2 reactants.  Beyond that number, we can not infer the implicit assumptions of the reaction rate as they are no longer considered "mass-action".  Thus, we require the modeler to write out the function of the reaction rate explicitly.

To do this, simply replace `rate=k1` with `propensity_function="k1*A*B/vol"`

See an example here:  https://github.com/GillesPy2/GillesPy2/blob/master/examples/BasicExamples/GeneticToggleSwitch.ipynb

I would caution the modeler to be carefully aware of the volume variable 'vol' in the creation of their `propensity_function`s, as it is very easy to miss this or get it wrong.
