### ISSUE TITLE
Bursting - is it supported?

### ISSUE THREAD

**Issue by Princeofthebow** [GillesPy2/GillesPy2#270]
Hello, as I'm tackling a problem regarding bursting I was wondering if the following notation is allowed and works:

products={MoleculeB: 1+np.random.binomial(1, 0..5,) }

In other word the production of mulecule B is a either 1 or 2 depending on the realisation of the the binomial.

Would this work as expected?

Edit: From the tests I have done it seems that the product is updated only at the first run and hence doing some thing as highlighted earlier would not be possible.

Can it be added as a feature?

**Comment by briandrawert** [comment]
Hi, 
The product is only updated once per model instantiation because the "np.random.binomial" function is evaluated when the model is created.  The resulting number is used for the simulation.

Due to the architecture of the simulators, implementing what you ask would be hard and would degrade the performance of our software dramatically.

However, there is a trivial way for you to build your model to create the bimodal behavior you are looking for.  Create two different reactions, one that produces 1 product, the other produces 2.  Give each rate=rate/2.  Then, when a reaction fires it will randomly pick one of those two reactions (based on the weight of their 'rate'), and produce either 1 or 2 'MoleculeB'.
