### ISSUE TITLE
Could you add the muti-threads support?

### ISSUE THREAD

**Issue by chenatf** [GillesPy2/GillesPy2#271]
Thanks for your work, it saves my time. However, In my application, even with the BasicTauHybridSolver(), it is still too slow for me. Do you have the plan to add the muti-threads support?

**Comment by briandrawert** [comment]
Depending on what your model is, the SSA-C solver is much faster than the BasicTauHybridSolver. If you can share some details about your model, we may be able to help you.

To directly answer your question, parallelization within a single simulation trajectory is not effective due to the nature of the simulation algorithm.  It is easy parallelize across realizations of a model, thus if you are simulating a large number of trajectories, simply break them up into smaller ensembles, simulate each on a separate processor and merge their result set.  This can be done with the Process python model, or use of Dask.

Please reply to this thread if you have any further questions.

**Comment by chenatf** [comment]
Thanks for your advice. For my model, the SSA-C solver is much faster.  
For parallelization, after thought the simulation algorithm, I agree with your advice.
